name: 'Mustache Template Action'
description: 'Parse mustache template files using environment variables as replacement'
inputs:
  input:  # id da entrada
    description: 'File location to input template'
    required: true
  output:
    description: 'Path for output file'
    required: true
  debug:
    description: 'Print the parsed content on console'
    required: false
    default: 'false'
outputs:
  time: # id da saída
    description: 'Time spent to parse the template'
runs:
  using: 'node12'
  main: 'dist/index.js'
